/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void btnStartClick(GButton source, GEvent event) { //_CODE_:btn_open:416458:
  println("btn_open - GButton >> GEvent." + event + " @ " + millis());
  ouverture_tsk();
} //_CODE_:btn_open:416458:

public void button1_click1(GButton source, GEvent event) { //_CODE_:btn_Sortie:717757:
  println("btn_Sortie - GButton >> GEvent." + event + " @ " + millis());
   sortie_tsk();
} //_CODE_:btn_Sortie:717757:

public void btn_fin_clk(GButton source, GEvent event) { //_CODE_:btn_fin:252657:
  println("btn_fin - GButton >> GEvent." + event + " @ " + millis());
  fin_tsk();
} //_CODE_:btn_fin:252657:

public void btn_debut_clk(GButton source, GEvent event) { //_CODE_:btn_debut:631903:
  println("btn_debut - GButton >> GEvent." + event + " @ " + millis());
  debutSoiree_tsk();
} //_CODE_:btn_debut:631903:

public void button1_click2(GButton source, GEvent event) { //_CODE_:button1:620558:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  defaultSong();
} //_CODE_:button1:620558:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:638463:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  vadorSong();
} //_CODE_:button2:638463:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:245694:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  pirateSong();
} //_CODE_:button3:245694:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:998570:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
  wrestlerSong();
} //_CODE_:button4:998570:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:856305:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
  mermaidSong();
} //_CODE_:button5:856305:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  btn_open = new GButton(this, 50, 270, 175, 200);
  btn_open.setText("Ouverture");
  btn_open.addEventHandler(this, "btnStartClick");
  btn_Sortie = new GButton(this, 370, 270, 175, 200);
  btn_Sortie.setText("Sortie");
  btn_Sortie.addEventHandler(this, "button1_click1");
  btn_fin = new GButton(this, 460, 520, 130, 70);
  btn_fin.setText("Fin Soirée");
  btn_fin.addEventHandler(this, "btn_fin_clk");
  btn_debut = new GButton(this, 10, 10, 130, 70);
  btn_debut.setText("Début soirée");
  btn_debut.addEventHandler(this, "btn_debut_clk");
  button1 = new GButton(this, 320, 50, 120, 40);
  button1.setText("De Base");
  button1.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button1.addEventHandler(this, "button1_click2");
  button2 = new GButton(this, 240, 110, 120, 40);
  button2.setText("Darth Vador");
  button2.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 400, 110, 120, 40);
  button3.setText("Pirate");
  button3.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 240, 180, 120, 40);
  button4.setText("Lutteur");
  button4.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 400, 180, 120, 40);
  button5.setText("Sirène");
  button5.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button5.addEventHandler(this, "button5_click1");
  label1 = new GLabel(this, 240, 10, 280, 40);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Choix Chansons");
  label1.setTextBold();
  label1.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton btn_open; 
GButton btn_Sortie; 
GButton btn_fin; 
GButton btn_debut; 
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
GLabel label1; 